import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Clapperboard, Play } from "lucide-react";

import Link from "next/link";

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<header className="p-4 border-b flex items-center justify-between">
					<h1 className="font-bold text-2xl flex gap-2 items-center">
						<Clapperboard />
						Next Movie
					</h1>
					<form className="flex items-center gap-1">
						<Input placeholder="Search" />
						<Button>Search</Button>
					</form>
				</header>
				<section className="flex">
					<aside className="p-4 border-r w-60 flex flex-col gap-1">
						<Button
                            asChild
							variant="outline"
							className="flex items-center justify-start">
							<Link
								href="/"
								className="flex gap-2 items-center justify-start">
								<Play />
								All Movies
							</Link>
						</Button>
						<Button
                            asChild
							variant="outline"
							className="flex items-center justify-start">
							<Link
								href="/genre/action/123"
								className="flex gap-2 items-center justify-start">
								<Play />
								Action
							</Link>
						</Button>
					</aside>
					<main className="p-4">{children}</main>
				</section>
			</body>
		</html>
	);
}
